---
- hosts: vagrantInstance
  vars_files:
    - 'defaults/main.yml'
    - 'vars/main.yml'

  tasks:
    - include: tasks/github.yml
      tags: ['install']

    - include: tasks/symfony2.yml

    - include: tasks/mysql.yml
      tags: ['db']

    - include: tasks/specific.yml
      tags: ['deploy']
