---
- name: GitHub | Does known_hosts file exists?
  stat: path={{ssh_facts.known_hosts}}
  register: st
  tags: [ 'github' ]

- name: GitHub | if not touch it
  file: dest={{ssh_facts.known_hosts}} state=touch
  when: not st.stat.exists
  tags: [ 'github' ]

- name: GitHub | Add known hosts to known_hosts file
  lineinfile: dest={{ssh_facts.known_hosts}} regexp=^${item.host} line="${item.line}"
  with_items:
  - {
    "host": "github.com",
    "line": "github.com,207.97.227.239 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
  }
  tags: [ 'github' ]

- name: GitHub | copy ssh key for github to the server
  copy: src={{github.key_file}} dest={{github.key_file_dest}} mode=0400
  tags: [ 'github' ]